# Generated by Django 4.1 on 2022-08-08 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auth0user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
