# Generated by Django 4.1 on 2022-08-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_testmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userid',
            name='auth0_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userid',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
