# Generated by Django 4.1 on 2022-08-12 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_user'),
        ('users', '0005_userid_auth0_id_alter_userid_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserID',
        ),
    ]
