# Generated by Django 4.1 on 2022-08-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_task_date_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_completed',
            field=models.CharField(default='dummy', max_length=100),
            preserve_default=False,
        ),
    ]
