# Generated by Django 4.1 on 2022-08-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='preset',
            name='category',
            field=models.CharField(default='Miscellaneous', max_length=50),
        ),
    ]
